;; init-ui.el

(load-theme 'solarized-dark t)

(tool-bar-mode -1)
(scroll-bar-mode -1)
(setq-default cursor-type 'bar)

(global-linum-mode t)
(global-hl-line-mode t)

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(set-face-attribute
 'default nil
 :font (font-spec :name "Source Code Pro"
                  :weight 'normal
                  :slant 'normal
                  :size 10.0))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font
   (frame-parameter nil 'font)
   charset
   (font-spec :name "汉仪楷体简"
              :weight 'normal
              :slant 'normal
              :size 12.0)))

(provide 'init-ui)
