;; init-ui.el

(load-theme 'solarized-dark t)

(tool-bar-mode -1)
(scroll-bar-mode -1)
(setq-default cursor-type 'bar)

(global-linum-mode t)
(global-hl-line-mode t)

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(set-face-attribute
 'default nil
 :font (font-spec :name "-outline-DejaVu Sans Mono-bold-italic-normal-mono-*-*-*-*-c-*-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 10.0))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font
   (frame-parameter nil 'font)
   charset
   (font-spec :name "-outline-文泉驿等宽微米黑-normal-normal-normal-sans-*-*-*-*-p-*-iso10646-1"
              :weight 'normal
              :slant 'normal
              :size 12.0)))

(provide 'init-ui)
